### PR TITLE
 Fetch Url Widget Repository behind corporate proxy (#1238)

### PR DESCRIPTION
**Pull request by tristanrobert**
## Context

With a self-hosted instance installed behind a corporate proxy, you cannot fetch a custom url widgets repository.

## Proposed solution
Add http proxy settings in order to be able to fetch url widget repository, for instance by reusing GRIST_HTTPS_PROXY and ProxyAgent.

## Related issues
#1238 

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [X] 🙅 no, because this is not relevant here
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by tristanrobert** [comment]
The e2e test AdminPanel does not show version ? (!)

**Comment by paulfitz** [comment]
> The e2e test AdminPanel does not show version ? (!)

This test may have become unreliable after a recent change. Will look into it.

**Comment by paulfitz** [comment]
> The e2e test AdminPanel does not show version ? (!)
(There's a possible fix for the flaky test coming, in the meantime I just reran it)

**Review by georgegevoian — APPROVED** [review]
Thanks @tristanrobert!

**Pull request merged**
