### PR TITLE
Run python tests during main workflow

### PR DESCRIPTION
**Pull request by georgegevoian**

### CODE REVIEW

**Comment by alexmojaki** [comment]
The XML output format isn't very human readable in the CI logs. Can you try without the `--xunit`?

**Comment by alexmojaki** [comment]
Please can you add `GREP_TESTS` to the table at the end of the README with an example command?

**Comment by paulfitz** [comment]
> Please can you add `GREP_TESTS` to the table at the end of the README with an example command?

Running tests might merit its own section. It will require `yarn run install:python` to have been run, and since the python version range supported for the tests is tight (3.9), it would be important to note that.

**Comment by alexmojaki** [comment]
>  It will require `yarn run install:python` to have been run

is anything really possible without that?

**Review by alexmojaki — APPROVED** [review]
Thanks!

**Pull request merged**
