### PR TITLE
Color header columns when a columns is colored

### PR DESCRIPTION
**Pull request by LouisDelbosc**
Related Issue #320 

I unshamely copy the code here: https://github.com/gristlabs/grist-core/blob/main/app/client/widgets/FieldBuilder.ts#L575

Screenshot 2022-11-10 at 17 41 00

### CODE REVIEW

**Comment by yohanboniface** [comment]
I'd suggest to colour only the header, not to infer with cell colour (like validation, and such). :)

**Comment by LouisDelbosc** [comment]
Is there a simple way to have the header a bit darker ? A slight change of the primary color ?

**Comment by georgegevoian** [comment]
> Is there a simple way to have the header a bit darker ? A slight change of the primary color ?

The first answer from [here](https://stackoverflow.com/questions/65297617/how-to-make-an-elements-background-color-a-little-darker-using-css) has a few ways you can do this with just CSS.

**Comment by georgegevoian** [comment]
Thanks for the PR @LouisDelbosc.

I do lean towards making this a new column-level setting rather than always inferring the color from the default column style. Inferring has some gotchas such as certain column settings modifying the default style (e.g. hyperlink text, toggle switches). Additionally, users may not always want the headers to be colored, so leaving that decision up to them would be better. I can see inferring being an additional option for this setting (used in place of a manually selected fill and text color) if it's still a feature that users would like. These are just some of my own thoughts - I'm not sure we've reached consensus yet on how this feature will work.

Based on the discussion in #320, it sounded like this would be a new setting that wasn't tied to the column style, but this PR is specifically for coloring the headers based on the column style. Is this intentional?

**Comment by LouisDelbosc** [comment]
> Based on the discussion in https://github.com/gristlabs/grist-core/issues/320, it sounded like this would be a new setting that wasn't tied to the column style, but this PR is specifically for coloring the headers based on the column style. Is this intentional?

Yes it is intentional @georgegevoian. Speaking with @vviers he suggested this feature as the quick win for excel user to groupe their column as in their spreadsheet. Maybe it is not the direction you would like to take, going straight to the grouping columns and I can understand.

@vviers could you add more argument otherwise we might choose to close this PR.

**Comment by vviers** [comment]
> I do lean towards making this a new column-level setting rather than always inferring the color from the default column style.

I'd agree with @georgegevoian on this one !

> Speaking with @vviers he suggested this feature as the quick win for excel user to groupe their column as in their spreadsheet.

Yes, header colors along with the ability to select and hide multiple columns at once would cover 80% of our users' needs with around 20% of the effort 🙂

**Comment by yohanboniface** [comment]
I also think a dedicated header setting would better suit the need. :)

**Pull request closed without merging**
