### PR TITLE
Add BooleanConverter to map proper boolean cells to a Bool column

### PR DESCRIPTION
**Pull request by yohanboniface**
While I'm warm! ;)

Note that only proper boolean will be considered, but not integers nor truthy or falsy strings.

cf #276

### CODE REVIEW

**Comment by paulfitz** [comment]
(the sporadic parseDate test failure is hopefully resolved now, if you care to rebase)

**Comment by alexmojaki** [comment]
Thanks @yohanboniface!

**Review by alexmojaki — APPROVED** [review]

**Comment by yohanboniface** [comment]
Thanks @alexmojaki :)

Now I remember asking to myself: why if all values of a column match the strings "true" or "false" we won't treat this as a bool candidate ?
Given this is how Grist itself will output a Bool column in CSV, it may make sense to accept those values back.

What do you think ? :)

**Comment by alexmojaki** [comment]
You should find that if a column only contains the exact strings `true` and `false`, then it will end up as a boolean column in the final table. But the process of parsing strings doesn't happen in Python, it happens here:

https://github.com/gristlabs/grist-core/blob/b1f5e061c1ca55ce36ca2ee76df66c5f86b802d4/app/common/ValueGuesser.ts#L88-L101

**Comment by yohanboniface** [comment]
Ah! Thanks for the pointer, I may have a python bias to see the world :D

**Pull request merged**
