### PR TITLE
[Tiny/refactoration] Move HomeDBManager to its own folder

### PR DESCRIPTION
**Pull request by fflorent**
This is a tiny and purely technical PR to move HomeDbManager to `homedb/index.ts`.

### CODE REVIEW

**Comment by berhalak** [comment]
Hi @fflorent. I like the idea of extracting `modules` from our lib folder. But I slightly prefer leaving the name of this file as it was. It is much easier to find it and it follows common patterns we already have.

**Comment by fflorent** [comment]
Hi @berhalak!

> Hi @fflorent. I like the idea of extracting modules from our lib folder. But I slightly prefer leaving the name of this file as it was. It is much easier to find it and it follows common patterns we already have.

OK, I prefer having the module inside the folder where there already is another module (`homedb/UsersManager.ts`).
That being said, I agree that a consistent pattern is more interesting.
So is it fine as it is to you (in such case, I may just close the PR)? Or should I rename the folder to `./homedbmanager`?

**Comment by fflorent** [comment]
Hi @berhalak !

OK, I have made the changes as requested.

**Review by berhalak — APPROVED** [review]
Thanks @fflorent !

**Pull request merged**
